namespace CatalogService.Data.Entities;

/// <summary>
/// Represents a product in the catalog.
/// Maps to the "products" table via EF Core conventions.
/// </summary>
public class Product
{
    /// <summary>
    /// Primary key. Generated by PostgreSQL as a sequential GUID
    /// for better index performance.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>Product display name (e.g., "Wireless Mouse")</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Detailed product description</summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Current price in USD. This is a snapshot - when an order is placed,
    /// the order stores the price at that moment. Price changes here
    /// don't affect existing orders.
    /// </summary>
    public decimal Price { get; set; }

    /// <summary>Product category for filtering (e.g., "Electronics")</summary>
    public string Category { get; set; } = string.Empty;

    /// <summary>
    /// Current available stock. Decremented when orders are placed.
    /// This is the "single source of truth" for inventory in the catalog.
    /// </summary>
    public int StockQuantity { get; set; }

    /// <summary>When the product was created</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>When the product was last updated</summary>
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}
